### ISSUE TITLE
build errors (eslint, ast, gjs)

### ISSUE THREAD

**Issue by yogo1212** [emiapwil/glassy-gnome#27]
In a fresh clone, just running make leaves me with this error:

```
£ make
npx eslint -c ./.eslintrc.js ./glassygnome@emiapwil/*.js
npx: installed 118 in 13.857s

Oops! Something went wrong! :(

ESLint: 7.30.0

ESLint couldn't find the plugin "eslint-plugin-gjs".

(The package "eslint-plugin-gjs" was not found when loaded as a Node module from the directory "/home/.../git/glassy-gnome".)

It's likely that the plugin isn't installed correctly. Try reinstalling by running the following:

    npm install eslint-plugin-gjs@latest --save-dev

The plugin "eslint-plugin-gjs" was referenced from the config file in "--config".

If you still can't figure out the problem, please stop by https://eslint.org/chat/help to chat with the team.

make: *** [Makefile:25: lint] Error 2
```

After doing that, there's another error:

```
£ make
npx eslint -c ./.eslintrc.js ./glassygnome@emiapwil/*.js
npx: installed 118 in 11.68s

Oops! Something went wrong! :(

ESLint: 7.30.0

Error: Failed to load plugin 'gjs' declared in '--config': Cannot find module 'eslint/lib/ast-utils'
Referenced from: /home/.../git/glassy-gnome/.eslintrc.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (/home/.../.npm/_npx/18511/lib/node_modules/eslint/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
    at Object.<anonymous> (/home/.../git/glassy-gnome/node_modules/eslint-plugin-gjs/lib/rules/translation-strings.js:8:18)
    at Module._compile (/home/.../.npm/_npx/18511/lib/node_modules/eslint/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
make: *** [Makefile:25: lint] Error 2
```

**Comment by yogo1212** [comment]
is `eslint-utils` the right thing to move to?
